# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: golang-webapp
  labels:
    app: golang-webapp
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: golang-webapp
  type: NodePort